/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package geopharma;

/**
 *
 * @author Kuidja Marco
 */
public class PharmaCart extends javax.swing.JPanel {

    /**
     * Creates new form PharmaCart
     * @param nom
     * @param jourOuvrable
     * @param heureOuvrable 
     */
    public PharmaCart(String nom, String jourOuvrable, String heureOuvrable) {
        initComponents();
        nomPharma.setText(nom);
        heureOvert.setText(heureOuvrable);
        jourOvert.setText(jourOuvrable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        nomPharma = new javax.swing.JLabel();
        jourOvert = new javax.swing.JLabel();
        heureOvert = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();

        jPanel11.setBackground(new java.awt.Color(153, 204, 255));
        jPanel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        nomPharma.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nomPharma.setForeground(new java.awt.Color(0, 153, 51));
        nomPharma.setText("Pharmacie Saint Piere");

        jourOvert.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jourOvert.setText("Lundi à Vendredi");

        heureOvert.setText(" 08h00 - 18h00");

        jButton15.setText("voir");
        jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton15MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomPharma)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jourOvert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(heureOvert)
                        .addGap(18, 18, 18)
                        .addComponent(jButton15)))
                .addGap(14, 14, 14))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(nomPharma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jourOvert, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(heureOvert))
                    .addComponent(jButton15, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseClicked
//        Map.open_Map(jPanel11);
    }//GEN-LAST:event_jButton15MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel heureOvert;
    private javax.swing.JButton jButton15;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JLabel jourOvert;
    private javax.swing.JLabel nomPharma;
    // End of variables declaration//GEN-END:variables
}
